- name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: pnpm
- name: Setup Pages
    uses: actions/configure-pages@v4
- name: Install dependencies
    run: pnpm install
- name: Build with VitePress
    run: pnpm docs:build